name: Test
on:
  # When pushing a new dist file
  push:
      paths:
        - index.dist.js
  # Or manually, upon request
  workflow_dispatch:
jobs:

  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: someimportantcompany/github-actions-ini-config@master
        uses: ./
        id: config
        with:
          config: |
            ; Here is a user comment
            [env]
            hello=world
            [outputs]
            hello2=world2
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env);
            console.log(JSON.parse(${{ toJSON(steps.config.outputs) }}));

  isolation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: someimportantcompany/github-actions-ini-config@master
        uses: ./
        id: config
        with:
          config: |
            ; Here is a user comment
            [env]
            hello=world
            [outputs]
            hello2=world2

            [(${ startsWith(github.ref, "refs/heads/") }).env]
            hello2=world
            [(${ startsWith(github.ref, "refs/heads/") }).outputs]
            hello=world

            [(${ startsWith(github.ref, "something/else/") }).env]
            hello=NOPE
            hello2=NOPE
            [(${ startsWith(github.ref, "something/else/") }).outputs]
            hello=NOPE
            hello2=NOPE
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env);
            console.log(JSON.parse(${{ toJSON(steps.config.outputs) }}));
